// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: raft.proto

package raftrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Raft_AppendEntriesInRaft_FullMethodName = "/Raft/AppendEntriesInRaft"
	Raft_HeartbeatInRaft_FullMethodName     = "/Raft/HeartbeatInRaft"
	Raft_RequestVote_FullMethodName         = "/Raft/RequestVote"
	Raft_InstallSSTable_FullMethodName      = "/Raft/InstallSSTable"
)

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftClient interface {
	AppendEntriesInRaft(ctx context.Context, in *AppendEntriesInRaftRequest, opts ...grpc.CallOption) (*AppendEntriesInRaftResponse, error)
	HeartbeatInRaft(ctx context.Context, in *AppendEntriesInRaftRequest, opts ...grpc.CallOption) (*AppendEntriesInRaftResponse, error)
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
	// InstallSSTable ships one span of the leader's state machine to a follower as
	// SSTable files (the LSM-Raft baseline). The follower ingests the files instead of
	// replaying the entries of that span. Client streaming: every message repeats the
	// span header, Data carries one chunk of one file.
	InstallSSTable(ctx context.Context, opts ...grpc.CallOption) (Raft_InstallSSTableClient, error)
}

type raftClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftClient(cc grpc.ClientConnInterface) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) AppendEntriesInRaft(ctx context.Context, in *AppendEntriesInRaftRequest, opts ...grpc.CallOption) (*AppendEntriesInRaftResponse, error) {
	out := new(AppendEntriesInRaftResponse)
	err := c.cc.Invoke(ctx, Raft_AppendEntriesInRaft_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) HeartbeatInRaft(ctx context.Context, in *AppendEntriesInRaftRequest, opts ...grpc.CallOption) (*AppendEntriesInRaftResponse, error) {
	out := new(AppendEntriesInRaftResponse)
	err := c.cc.Invoke(ctx, Raft_HeartbeatInRaft_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := c.cc.Invoke(ctx, Raft_RequestVote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) InstallSSTable(ctx context.Context, opts ...grpc.CallOption) (Raft_InstallSSTableClient, error) {
	stream, err := c.cc.NewStream(ctx, &Raft_ServiceDesc.Streams[0], Raft_InstallSSTable_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &raftInstallSSTableClient{stream}
	return x, nil
}

type Raft_InstallSSTableClient interface {
	Send(*InstallSSTableRequest) error
	CloseAndRecv() (*InstallSSTableResponse, error)
	grpc.ClientStream
}

type raftInstallSSTableClient struct {
	grpc.ClientStream
}

func (x *raftInstallSSTableClient) Send(m *InstallSSTableRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *raftInstallSSTableClient) CloseAndRecv() (*InstallSSTableResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(InstallSSTableResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RaftServer is the server API for Raft service.
// All implementations must embed UnimplementedRaftServer
// for forward compatibility
type RaftServer interface {
	AppendEntriesInRaft(context.Context, *AppendEntriesInRaftRequest) (*AppendEntriesInRaftResponse, error)
	HeartbeatInRaft(context.Context, *AppendEntriesInRaftRequest) (*AppendEntriesInRaftResponse, error)
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	// InstallSSTable ships one span of the leader's state machine to a follower as
	// SSTable files (the LSM-Raft baseline). The follower ingests the files instead of
	// replaying the entries of that span. Client streaming: every message repeats the
	// span header, Data carries one chunk of one file.
	InstallSSTable(Raft_InstallSSTableServer) error
	mustEmbedUnimplementedRaftServer()
}

// UnimplementedRaftServer must be embedded to have forward compatible implementations.
type UnimplementedRaftServer struct {
}

func (UnimplementedRaftServer) AppendEntriesInRaft(context.Context, *AppendEntriesInRaftRequest) (*AppendEntriesInRaftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntriesInRaft not implemented")
}
func (UnimplementedRaftServer) HeartbeatInRaft(context.Context, *AppendEntriesInRaftRequest) (*AppendEntriesInRaftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatInRaft not implemented")
}
func (UnimplementedRaftServer) RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedRaftServer) InstallSSTable(Raft_InstallSSTableServer) error {
	return status.Errorf(codes.Unimplemented, "method InstallSSTable not implemented")
}
func (UnimplementedRaftServer) mustEmbedUnimplementedRaftServer() {}

// UnsafeRaftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftServer will
// result in compilation errors.
type UnsafeRaftServer interface {
	mustEmbedUnimplementedRaftServer()
}

func RegisterRaftServer(s grpc.ServiceRegistrar, srv RaftServer) {
	s.RegisterService(&Raft_ServiceDesc, srv)
}

func _Raft_AppendEntriesInRaft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesInRaftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntriesInRaft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raft_AppendEntriesInRaft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntriesInRaft(ctx, req.(*AppendEntriesInRaftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_HeartbeatInRaft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesInRaftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).HeartbeatInRaft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raft_HeartbeatInRaft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).HeartbeatInRaft(ctx, req.(*AppendEntriesInRaftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raft_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_InstallSSTable_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftServer).InstallSSTable(&raftInstallSSTableServer{stream})
}

type Raft_InstallSSTableServer interface {
	SendAndClose(*InstallSSTableResponse) error
	Recv() (*InstallSSTableRequest, error)
	grpc.ServerStream
}

type raftInstallSSTableServer struct {
	grpc.ServerStream
}

func (x *raftInstallSSTableServer) SendAndClose(m *InstallSSTableResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *raftInstallSSTableServer) Recv() (*InstallSSTableRequest, error) {
	m := new(InstallSSTableRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Raft_ServiceDesc is the grpc.ServiceDesc for Raft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Raft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntriesInRaft",
			Handler:    _Raft_AppendEntriesInRaft_Handler,
		},
		{
			MethodName: "HeartbeatInRaft",
			Handler:    _Raft_HeartbeatInRaft_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InstallSSTable",
			Handler:       _Raft_InstallSSTable_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "raft.proto",
}
