// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: raft.proto

package raftrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallSSTableStatus int32

const (
	InstallSSTableStatus_INGESTED   InstallSSTableStatus = 0 // files ingested, Applied == SpanEnd
	InstallSSTableStatus_SKIPPED    InstallSSTableStatus = 1 // follower had already applied through SpanEnd
	InstallSSTableStatus_GAP        InstallSSTableStatus = 2 // follower's Applied < SpanStart-1; resend from Applied+1
	InstallSSTableStatus_STALE_TERM InstallSSTableStatus = 3 // Term is older than the follower's term
	InstallSSTableStatus_FAILED     InstallSSTableStatus = 4 // ingestion error, see the follower log
)

// Enum value maps for InstallSSTableStatus.
var (
	InstallSSTableStatus_name = map[int32]string{
		0: "INGESTED",
		1: "SKIPPED",
		2: "GAP",
		3: "STALE_TERM",
		4: "FAILED",
	}
	InstallSSTableStatus_value = map[string]int32{
		"INGESTED":   0,
		"SKIPPED":    1,
		"GAP":        2,
		"STALE_TERM": 3,
		"FAILED":     4,
	}
)

func (x InstallSSTableStatus) Enum() *InstallSSTableStatus {
	p := new(InstallSSTableStatus)
	*p = x
	return p
}

func (x InstallSSTableStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallSSTableStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_proto_enumTypes[0].Descriptor()
}

func (InstallSSTableStatus) Type() protoreflect.EnumType {
	return &file_raft_proto_enumTypes[0]
}

func (x InstallSSTableStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallSSTableStatus.Descriptor instead.
func (InstallSSTableStatus) EnumDescriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

type AppendEntriesInRaftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=LeaderId,proto3" json:"LeaderId,omitempty"`
	PrevLogIndex  int32                  `protobuf:"varint,3,opt,name=PrevLogIndex,proto3" json:"PrevLogIndex,omitempty"`
	PrevLogTerm   int32                  `protobuf:"varint,4,opt,name=PrevLogTerm,proto3" json:"PrevLogTerm,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,5,rep,name=Entries,proto3" json:"Entries,omitempty"`
	LeaderCommit  int32                  `protobuf:"varint,6,opt,name=LeaderCommit,proto3" json:"LeaderCommit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesInRaftRequest) Reset() {
	*x = AppendEntriesInRaftRequest{}
	mi := &file_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesInRaftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesInRaftRequest) ProtoMessage() {}

func (x *AppendEntriesInRaftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesInRaftRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesInRaftRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

func (x *AppendEntriesInRaftRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesInRaftRequest) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AppendEntriesInRaftRequest) GetPrevLogIndex() int32 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesInRaftRequest) GetPrevLogTerm() int32 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesInRaftRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesInRaftRequest) GetLeaderCommit() int32 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *DetailCod             `protobuf:"bytes,1,opt,name=Command,proto3" json:"Command,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetCommand() *DetailCod {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *LogEntry) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

type DetailCod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	OpType        string                 `protobuf:"bytes,3,opt,name=OpType,proto3" json:"OpType,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=Value,proto3" json:"Value,omitempty"`
	SeqId         int64                  `protobuf:"varint,6,opt,name=SeqId,proto3" json:"SeqId,omitempty"`
	ClientId      int64                  `protobuf:"varint,7,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	FileVersion   int64                  `protobuf:"varint,8,opt,name=FileVersion,proto3" json:"FileVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailCod) Reset() {
	*x = DetailCod{}
	mi := &file_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailCod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailCod) ProtoMessage() {}

func (x *DetailCod) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailCod.ProtoReflect.Descriptor instead.
func (*DetailCod) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{2}
}

func (x *DetailCod) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DetailCod) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *DetailCod) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *DetailCod) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DetailCod) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DetailCod) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *DetailCod) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *DetailCod) GetFileVersion() int64 {
	if x != nil {
		return x.FileVersion
	}
	return 0
}

type AppendEntriesInRaftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	ConflictIndex int32                  `protobuf:"varint,3,opt,name=ConflictIndex,proto3" json:"ConflictIndex,omitempty"`
	ConflictTerm  int32                  `protobuf:"varint,4,opt,name=ConflictTerm,proto3" json:"ConflictTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesInRaftResponse) Reset() {
	*x = AppendEntriesInRaftResponse{}
	mi := &file_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesInRaftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesInRaftResponse) ProtoMessage() {}

func (x *AppendEntriesInRaftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesInRaftResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesInRaftResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEntriesInRaftResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesInRaftResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesInRaftResponse) GetConflictIndex() int32 {
	if x != nil {
		return x.ConflictIndex
	}
	return 0
}

func (x *AppendEntriesInRaftResponse) GetConflictTerm() int32 {
	if x != nil {
		return x.ConflictTerm
	}
	return 0
}

type RequestVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	CandidateId   int32                  `protobuf:"varint,2,opt,name=CandidateId,proto3" json:"CandidateId,omitempty"`
	LastLogIndex  int32                  `protobuf:"varint,3,opt,name=LastLogIndex,proto3" json:"LastLogIndex,omitempty"`
	LastLogTerm   int32                  `protobuf:"varint,4,opt,name=LastLogTerm,proto3" json:"LastLogTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVoteRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidateId() int32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogIndex() int32 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() int32 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=VoteGranted,proto3" json:"VoteGranted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{5}
}

func (x *RequestVoteResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type InstallSSTableRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Term            int32                  `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	LeaderId        int32                  `protobuf:"varint,2,opt,name=LeaderId,proto3" json:"LeaderId,omitempty"`
	SpanStart       int64                  `protobuf:"varint,3,opt,name=SpanStart,proto3" json:"SpanStart,omitempty"`             // first log index the span covers, inclusive
	SpanEnd         int64                  `protobuf:"varint,4,opt,name=SpanEnd,proto3" json:"SpanEnd,omitempty"`                 // last log index the span covers, inclusive
	OldestAvailable int64                  `protobuf:"varint,5,opt,name=OldestAvailable,proto3" json:"OldestAvailable,omitempty"` // start of the oldest span the leader can still send (0 = unknown)
	FileName        string                 `protobuf:"bytes,6,opt,name=FileName,proto3" json:"FileName,omitempty"`                // basename of the file this chunk belongs to
	FileSeq         int32                  `protobuf:"varint,7,opt,name=FileSeq,proto3" json:"FileSeq,omitempty"`                 // ingestion order of FileName within the span, from 0
	FileCount       int32                  `protobuf:"varint,8,opt,name=FileCount,proto3" json:"FileCount,omitempty"`             // number of files in the span
	Offset          int64                  `protobuf:"varint,9,opt,name=Offset,proto3" json:"Offset,omitempty"`                   // byte offset of Data inside FileName
	Data            []byte                 `protobuf:"bytes,10,opt,name=Data,proto3" json:"Data,omitempty"`
	Last            bool                   `protobuf:"varint,11,opt,name=Last,proto3" json:"Last,omitempty"` // final chunk of the span
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InstallSSTableRequest) Reset() {
	*x = InstallSSTableRequest{}
	mi := &file_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSSTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSSTableRequest) ProtoMessage() {}

func (x *InstallSSTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSSTableRequest.ProtoReflect.Descriptor instead.
func (*InstallSSTableRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{6}
}

func (x *InstallSSTableRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSSTableRequest) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *InstallSSTableRequest) GetSpanStart() int64 {
	if x != nil {
		return x.SpanStart
	}
	return 0
}

func (x *InstallSSTableRequest) GetSpanEnd() int64 {
	if x != nil {
		return x.SpanEnd
	}
	return 0
}

func (x *InstallSSTableRequest) GetOldestAvailable() int64 {
	if x != nil {
		return x.OldestAvailable
	}
	return 0
}

func (x *InstallSSTableRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *InstallSSTableRequest) GetFileSeq() int32 {
	if x != nil {
		return x.FileSeq
	}
	return 0
}

func (x *InstallSSTableRequest) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *InstallSSTableRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *InstallSSTableRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InstallSSTableRequest) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

type InstallSSTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Applied       int64                  `protobuf:"varint,2,opt,name=Applied,proto3" json:"Applied,omitempty"`
	Status        InstallSSTableStatus   `protobuf:"varint,3,opt,name=Status,proto3,enum=InstallSSTableStatus" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSSTableResponse) Reset() {
	*x = InstallSSTableResponse{}
	mi := &file_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSSTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSSTableResponse) ProtoMessage() {}

func (x *InstallSSTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSSTableResponse.ProtoReflect.Descriptor instead.
func (*InstallSSTableResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{7}
}

func (x *InstallSSTableResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSSTableResponse) GetApplied() int64 {
	if x != nil {
		return x.Applied
	}
	return 0
}

func (x *InstallSSTableResponse) GetStatus() InstallSSTableStatus {
	if x != nil {
		return x.Status
	}
	return InstallSSTableStatus_INGESTED
}

var File_raft_proto protoreflect.FileDescriptor

const file_raft_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"raft.proto\"\xdb\x01\n" +
	"\x1aAppendEntriesInRaftRequest\x12\x12\n" +
	"\x04Term\x18\x01 \x01(\x05R\x04Term\x12\x1a\n" +
	"\bLeaderId\x18\x02 \x01(\x05R\bLeaderId\x12\"\n" +
	"\fPrevLogIndex\x18\x03 \x01(\x05R\fPrevLogIndex\x12 \n" +
	"\vPrevLogTerm\x18\x04 \x01(\x05R\vPrevLogTerm\x12#\n" +
	"\aEntries\x18\x05 \x03(\v2\t.LogEntryR\aEntries\x12\"\n" +
	"\fLeaderCommit\x18\x06 \x01(\x05R\fLeaderCommit\"D\n" +
	"\bLogEntry\x12$\n" +
	"\aCommand\x18\x01 \x01(\v2\n" +
	".DetailCodR\aCommand\x12\x12\n" +
	"\x04Term\x18\x02 \x01(\x05R\x04Term\"\xc9\x01\n" +
	"\tDetailCod\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\x05R\x05Index\x12\x12\n" +
	"\x04Term\x18\x02 \x01(\x05R\x04Term\x12\x16\n" +
	"\x06OpType\x18\x03 \x01(\tR\x06OpType\x12\x10\n" +
	"\x03Key\x18\x04 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x05 \x01(\tR\x05Value\x12\x14\n" +
	"\x05SeqId\x18\x06 \x01(\x03R\x05SeqId\x12\x1a\n" +
	"\bClientId\x18\a \x01(\x03R\bClientId\x12 \n" +
	"\vFileVersion\x18\b \x01(\x03R\vFileVersion\"\x95\x01\n" +
	"\x1bAppendEntriesInRaftResponse\x12\x12\n" +
	"\x04Term\x18\x01 \x01(\x05R\x04Term\x12\x18\n" +
	"\aSuccess\x18\x02 \x01(\bR\aSuccess\x12$\n" +
	"\rConflictIndex\x18\x03 \x01(\x05R\rConflictIndex\x12\"\n" +
	"\fConflictTerm\x18\x04 \x01(\x05R\fConflictTerm\"\x90\x01\n" +
	"\x12RequestVoteRequest\x12\x12\n" +
	"\x04Term\x18\x01 \x01(\x05R\x04Term\x12 \n" +
	"\vCandidateId\x18\x02 \x01(\x05R\vCandidateId\x12\"\n" +
	"\fLastLogIndex\x18\x03 \x01(\x05R\fLastLogIndex\x12 \n" +
	"\vLastLogTerm\x18\x04 \x01(\x05R\vLastLogTerm\"K\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04Term\x18\x01 \x01(\x05R\x04Term\x12 \n" +
	"\vVoteGranted\x18\x02 \x01(\bR\vVoteGranted\"\xbd\x02\n" +
	"\x15InstallSSTableRequest\x12\x12\n" +
	"\x04Term\x18\x01 \x01(\x05R\x04Term\x12\x1a\n" +
	"\bLeaderId\x18\x02 \x01(\x05R\bLeaderId\x12\x1c\n" +
	"\tSpanStart\x18\x03 \x01(\x03R\tSpanStart\x12\x18\n" +
	"\aSpanEnd\x18\x04 \x01(\x03R\aSpanEnd\x12(\n" +
	"\x0fOldestAvailable\x18\x05 \x01(\x03R\x0fOldestAvailable\x12\x1a\n" +
	"\bFileName\x18\x06 \x01(\tR\bFileName\x12\x18\n" +
	"\aFileSeq\x18\a \x01(\x05R\aFileSeq\x12\x1c\n" +
	"\tFileCount\x18\b \x01(\x05R\tFileCount\x12\x16\n" +
	"\x06Offset\x18\t \x01(\x03R\x06Offset\x12\x12\n" +
	"\x04Data\x18\n" +
	" \x01(\fR\x04Data\x12\x12\n" +
	"\x04Last\x18\v \x01(\bR\x04Last\"u\n" +
	"\x16InstallSSTableResponse\x12\x12\n" +
	"\x04Term\x18\x01 \x01(\x05R\x04Term\x12\x18\n" +
	"\aApplied\x18\x02 \x01(\x03R\aApplied\x12-\n" +
	"\x06Status\x18\x03 \x01(\x0e2\x15.InstallSSTableStatusR\x06Status*V\n" +
	"\x14InstallSSTableStatus\x12\f\n" +
	"\bINGESTED\x10\x00\x12\v\n" +
	"\aSKIPPED\x10\x01\x12\a\n" +
	"\x03GAP\x10\x02\x12\x0e\n" +
	"\n" +
	"STALE_TERM\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xad\x02\n" +
	"\x04Raft\x12R\n" +
	"\x13AppendEntriesInRaft\x12\x1b.AppendEntriesInRaftRequest\x1a\x1c.AppendEntriesInRaftResponse\"\x00\x12N\n" +
	"\x0fHeartbeatInRaft\x12\x1b.AppendEntriesInRaftRequest\x1a\x1c.AppendEntriesInRaftResponse\"\x00\x12:\n" +
	"\vRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\"\x00\x12E\n" +
	"\x0eInstallSSTable\x12\x16.InstallSSTableRequest\x1a\x17.InstallSSTableResponse\"\x00(\x01B\fZ\n" +
	"./;raftrpcb\x06proto3"

var (
	file_raft_proto_rawDescOnce sync.Once
	file_raft_proto_rawDescData []byte
)

func file_raft_proto_rawDescGZIP() []byte {
	file_raft_proto_rawDescOnce.Do(func() {
		file_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)))
	})
	return file_raft_proto_rawDescData
}

var file_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_raft_proto_goTypes = []any{
	(InstallSSTableStatus)(0),           // 0: InstallSSTableStatus
	(*AppendEntriesInRaftRequest)(nil),  // 1: AppendEntriesInRaftRequest
	(*LogEntry)(nil),                    // 2: LogEntry
	(*DetailCod)(nil),                   // 3: DetailCod
	(*AppendEntriesInRaftResponse)(nil), // 4: AppendEntriesInRaftResponse
	(*RequestVoteRequest)(nil),          // 5: RequestVoteRequest
	(*RequestVoteResponse)(nil),         // 6: RequestVoteResponse
	(*InstallSSTableRequest)(nil),       // 7: InstallSSTableRequest
	(*InstallSSTableResponse)(nil),      // 8: InstallSSTableResponse
}
var file_raft_proto_depIdxs = []int32{
	2, // 0: AppendEntriesInRaftRequest.Entries:type_name -> LogEntry
	3, // 1: LogEntry.Command:type_name -> DetailCod
	0, // 2: InstallSSTableResponse.Status:type_name -> InstallSSTableStatus
	1, // 3: Raft.AppendEntriesInRaft:input_type -> AppendEntriesInRaftRequest
	1, // 4: Raft.HeartbeatInRaft:input_type -> AppendEntriesInRaftRequest
	5, // 5: Raft.RequestVote:input_type -> RequestVoteRequest
	7, // 6: Raft.InstallSSTable:input_type -> InstallSSTableRequest
	4, // 7: Raft.AppendEntriesInRaft:output_type -> AppendEntriesInRaftResponse
	4, // 8: Raft.HeartbeatInRaft:output_type -> AppendEntriesInRaftResponse
	6, // 9: Raft.RequestVote:output_type -> RequestVoteResponse
	8, // 10: Raft.InstallSSTable:output_type -> InstallSSTableResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_raft_proto_init() }
func file_raft_proto_init() {
	if File_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raft_proto_goTypes,
		DependencyIndexes: file_raft_proto_depIdxs,
		EnumInfos:         file_raft_proto_enumTypes,
		MessageInfos:      file_raft_proto_msgTypes,
	}.Build()
	File_raft_proto = out.File
	file_raft_proto_goTypes = nil
	file_raft_proto_depIdxs = nil
}
