// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: kv.proto

package kvrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInRaftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	SeqId         int64                  `protobuf:"varint,3,opt,name=SeqId,proto3" json:"SeqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInRaftRequest) Reset() {
	*x = GetInRaftRequest{}
	mi := &file_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInRaftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInRaftRequest) ProtoMessage() {}

func (x *GetInRaftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInRaftRequest.ProtoReflect.Descriptor instead.
func (*GetInRaftRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetInRaftRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetInRaftRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *GetInRaftRequest) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type GetInRaftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=Err,proto3" json:"Err,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	LeaderId      int32                  `protobuf:"varint,3,opt,name=LeaderId,proto3" json:"LeaderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInRaftResponse) Reset() {
	*x = GetInRaftResponse{}
	mi := &file_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInRaftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInRaftResponse) ProtoMessage() {}

func (x *GetInRaftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInRaftResponse.ProtoReflect.Descriptor instead.
func (*GetInRaftResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetInRaftResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *GetInRaftResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetInRaftResponse) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type PutInRaftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Op            string                 `protobuf:"bytes,3,opt,name=Op,proto3" json:"Op,omitempty"`
	ClientId      int64                  `protobuf:"varint,4,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	SeqId         int64                  `protobuf:"varint,5,opt,name=SeqId,proto3" json:"SeqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutInRaftRequest) Reset() {
	*x = PutInRaftRequest{}
	mi := &file_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutInRaftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutInRaftRequest) ProtoMessage() {}

func (x *PutInRaftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutInRaftRequest.ProtoReflect.Descriptor instead.
func (*PutInRaftRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutInRaftRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutInRaftRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutInRaftRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *PutInRaftRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *PutInRaftRequest) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type PutInRaftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=Err,proto3" json:"Err,omitempty"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=LeaderId,proto3" json:"LeaderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutInRaftResponse) Reset() {
	*x = PutInRaftResponse{}
	mi := &file_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutInRaftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutInRaftResponse) ProtoMessage() {}

func (x *PutInRaftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutInRaftResponse.ProtoReflect.Descriptor instead.
func (*PutInRaftResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutInRaftResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *PutInRaftResponse) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type ScanRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      string                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        string                 `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRangeRequest) Reset() {
	*x = ScanRangeRequest{}
	mi := &file_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRangeRequest) ProtoMessage() {}

func (x *ScanRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRangeRequest.ProtoReflect.Descriptor instead.
func (*ScanRangeRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{4}
}

func (x *ScanRangeRequest) GetStartKey() string {
	if x != nil {
		return x.StartKey
	}
	return ""
}

func (x *ScanRangeRequest) GetEndKey() string {
	if x != nil {
		return x.EndKey
	}
	return ""
}

type ScanRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyValuePairs map[string]string      `protobuf:"bytes,1,rep,name=key_value_pairs,json=keyValuePairs,proto3" json:"key_value_pairs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=LeaderId,proto3" json:"LeaderId,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=Err,proto3" json:"Err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRangeResponse) Reset() {
	*x = ScanRangeResponse{}
	mi := &file_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRangeResponse) ProtoMessage() {}

func (x *ScanRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRangeResponse.ProtoReflect.Descriptor instead.
func (*ScanRangeResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{5}
}

func (x *ScanRangeResponse) GetKeyValuePairs() map[string]string {
	if x != nil {
		return x.KeyValuePairs
	}
	return nil
}

func (x *ScanRangeResponse) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *ScanRangeResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_kv_proto protoreflect.FileDescriptor

const file_kv_proto_rawDesc = "" +
	"\n" +
	"\bkv.proto\"V\n" +
	"\x10GetInRaftRequest\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x1a\n" +
	"\bClientId\x18\x02 \x01(\x03R\bClientId\x12\x14\n" +
	"\x05SeqId\x18\x03 \x01(\x03R\x05SeqId\"W\n" +
	"\x11GetInRaftResponse\x12\x10\n" +
	"\x03Err\x18\x01 \x01(\tR\x03Err\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\x12\x1a\n" +
	"\bLeaderId\x18\x03 \x01(\x05R\bLeaderId\"|\n" +
	"\x10PutInRaftRequest\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\x12\x0e\n" +
	"\x02Op\x18\x03 \x01(\tR\x02Op\x12\x1a\n" +
	"\bClientId\x18\x04 \x01(\x03R\bClientId\x12\x14\n" +
	"\x05SeqId\x18\x05 \x01(\x03R\x05SeqId\"A\n" +
	"\x11PutInRaftResponse\x12\x10\n" +
	"\x03Err\x18\x01 \x01(\tR\x03Err\x12\x1a\n" +
	"\bLeaderId\x18\x02 \x01(\x05R\bLeaderId\"H\n" +
	"\x10ScanRangeRequest\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\tR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\tR\x06endKey\"\xd2\x01\n" +
	"\x11ScanRangeResponse\x12M\n" +
	"\x0fkey_value_pairs\x18\x01 \x03(\v2%.ScanRangeResponse.KeyValuePairsEntryR\rkeyValuePairs\x12\x1a\n" +
	"\bLeaderId\x18\x02 \x01(\x05R\bLeaderId\x12\x10\n" +
	"\x03Err\x18\x03 \x01(\tR\x03Err\x1a@\n" +
	"\x12KeyValuePairsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xac\x01\n" +
	"\x02KV\x124\n" +
	"\tGetInRaft\x12\x11.GetInRaftRequest\x1a\x12.GetInRaftResponse\"\x00\x12:\n" +
	"\x0fScanRangeInRaft\x12\x11.ScanRangeRequest\x1a\x12.ScanRangeResponse\"\x00\x124\n" +
	"\tPutInRaft\x12\x11.PutInRaftRequest\x1a\x12.PutInRaftResponse\"\x00B\n" +
	"Z\b./;kvrpcb\x06proto3"

var (
	file_kv_proto_rawDescOnce sync.Once
	file_kv_proto_rawDescData []byte
)

func file_kv_proto_rawDescGZIP() []byte {
	file_kv_proto_rawDescOnce.Do(func() {
		file_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)))
	})
	return file_kv_proto_rawDescData
}

var file_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kv_proto_goTypes = []any{
	(*GetInRaftRequest)(nil),  // 0: GetInRaftRequest
	(*GetInRaftResponse)(nil), // 1: GetInRaftResponse
	(*PutInRaftRequest)(nil),  // 2: PutInRaftRequest
	(*PutInRaftResponse)(nil), // 3: PutInRaftResponse
	(*ScanRangeRequest)(nil),  // 4: ScanRangeRequest
	(*ScanRangeResponse)(nil), // 5: ScanRangeResponse
	nil,                       // 6: ScanRangeResponse.KeyValuePairsEntry
}
var file_kv_proto_depIdxs = []int32{
	6, // 0: ScanRangeResponse.key_value_pairs:type_name -> ScanRangeResponse.KeyValuePairsEntry
	0, // 1: KV.GetInRaft:input_type -> GetInRaftRequest
	4, // 2: KV.ScanRangeInRaft:input_type -> ScanRangeRequest
	2, // 3: KV.PutInRaft:input_type -> PutInRaftRequest
	1, // 4: KV.GetInRaft:output_type -> GetInRaftResponse
	5, // 5: KV.ScanRangeInRaft:output_type -> ScanRangeResponse
	3, // 6: KV.PutInRaft:output_type -> PutInRaftResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kv_proto_init() }
func file_kv_proto_init() {
	if File_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kv_proto_goTypes,
		DependencyIndexes: file_kv_proto_depIdxs,
		MessageInfos:      file_kv_proto_msgTypes,
	}.Build()
	File_kv_proto = out.File
	file_kv_proto_goTypes = nil
	file_kv_proto_depIdxs = nil
}
